### ISSUE TITLE
A11y - Détail d'un article - lien dans les outils ne sont pas conforme

### ISSUE THREAD

**Issue by cr2a-graphique** [c3rb-org/template_RGAA_C3rb#12]
Les boutons imprimer, editer et email ont un libéllé et un title identique. 
Soit supprimer le title soit le modifier

**Comment by Biromain** [comment]
C'est écrit en dur dans le helper `icon` de `com_content` [Lien](https://github.com/joomla/joomla-cms/blob/staging/components/com_content/helpers/icon.php#L107) Ligne 107,110 266,269

**Comment by cr2a-graphique** [comment]
Ok merci,
je vais essayer de faire une issue sur Joomlacms.

**Comment by cr2a-graphique** [comment]
Issue Joomlacms : https://github.com/joomla/joomla-cms/issues/8694

En attendant j'ai refais la view ...

**Comment by cr2a-graphique** [comment]
fix by d1b1f551b9b9f29bfb219eb701dd7c0d743615bd
