### ISSUE TITLE
Menu principal absent si réduction de la fenêtre.

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#15]
Quand je réduis la fenêtre de mon navigateur, le bouton du menu réduit s'affiche bien en lieu et place du menu principal. Mais ce dernier n'affiche pas le menu déroulant.

Résultat attentu : naviguer dans le site depuis un appareil mobile.

**Comment by cr2a-graphique** [comment]
Le menu doit avoir une id unique.
fixé avec le commit : 67ea118.

Attention cependant a ne pas avoir de taille fixe sur la hauteur de ton menu, celle ci empêcherait le menu rwd de s'ouvrir.
