### ISSUE TITLE
Style de template

### ISSUE THREAD

**Issue by Ludovic-C3rb** [c3rb-org/template_RGAA_C3rb#17]
Serait-il possible d'avoir la main depuis la gestion de style du template de paramétrer différemment l'affichage du menu principal, de colonne de droite et / ou gauche et pied de page?

**Comment by cr2a-graphique** [comment]
Plus de précisions stp, des exemples, ou bien même du code.

**Comment by Ludovic-C3rb** [comment]
Serait-il possible que lorsque l'on modifie le menu principal, cela n'ait pas d'impacts sur les module menu en colonne de droite, gauche ou pied de page.
![modification-style-menu](https://cloud.githubusercontent.com/assets/10918914/10571964/31b7d64e-7644-11e5-9419-043dfecb261a.png).

**Comment by cr2a-graphique** [comment]
Dans le cas d'un modèle de conception ?

**Comment by jeromec3rb** [comment]
Je complète cette issue ayant rencontré le problème suivant :

J'utilise les paramètres "pro" depuis l'administration afin de modifier mon habillage.
Je rencontre un problème vis à vis des menus.

Le style est en effet bien appliqué si je ne modifie pas les paramètres d'affichage depuis le module.
Mais si je crée par exemple un module de menu, avec en paramètre d'affichage avancé le style "vertical", les renseignements renseignés dans le style du template ne sont pas reproduits.

**Comment by cr2a-graphique** [comment]
A partir de la version 1.1.4 les menu sont stylisable unitairement (une config pour le defaul, une pour le mega, une pour le vertical etc)

**Comment by cr2a-graphique** [comment]
Fix par f100d8084cb74b1064fc064070b98c5296889e82
