### ISSUE TITLE
Class de position

### ISSUE THREAD

**Issue by Ludovic-C3rb** [c3rb-org/template_RGAA_C3rb#18]
Serait-il possible d'avoir une class pour cibler tous les modules d'une position. Par exemple avoir la class position1 pour tous les modules mis dans la position1.

**Comment by cr2a-graphique** [comment]
Ok, c'est fait je t'ai groupé les layouts et chacune des positions.
Regarde le commit f3ba9b8 

Si tu veux des agencements particuliés hésites pas à détailler plus tes issues et écrire du code.
