### ISSUE TITLE
Favicon.ico non mis à jour (cache)

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#20]
Étapes pour reproduire le problème ( Steps to reproduce the issue )

Installation des nouveaux favicon dans le template :
- Génération des accès aux favicons dans le head.php.
- Copier/coller des favicons dans le dossier templates/images/template/favicon/.

Résultat attendu ( Expected result )

Le nouveau favicon doit apparaitre dans le navigateur. Pour cela, le favicon.ico doit avoir remplacé l'ancien dans le dossier templates/images/template/favicon/.

Résultat Actuel ( Actual result )

Le favicon.ico reste inchangé. Si on copie ce dernier, dont la miniature représente le nouveau favicon, dans le dossier favicon du template comprenant l'existant, il reprendra l'apparence de l'ancien.

Informations système ( System information (as much as possible) )

Système local.

Commentaires ( Additional comments )

Problème de cache
En solution alternative, j'ai déplacé le favicon.ico dans le dossier racine du template et modifié son accès depuis le head.php.

**Comment by cr2a-graphique** [comment]
Pour FireFox la favicon doit être placée dans le dossier racine du template.
