### ISSUE TITLE
Bug de prise en compte du paramètre

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#25]
Lien de menu Blog > Catégorie >  Titre de la catégorie
MASQUER

Vue `category > blog.php`
```php 
if ($this->params->get('show_category_heading_title_text', 1) == 1) :
```

Il faut mettre à 0 .

**Comment by Biromain** [comment]
Titre de la catégorie est branché sur `show_category_title`

`show_category_heading_title_text` est pour Texte des sous-catégories

**Comment by Fuzariane** [comment]
Alors je comprends pas pourquoi ma modif fonctionne ?

**Comment by Fuzariane** [comment]
... et pourtant, le paramètre est pris en compte à ce niveau là. Bug du core ?

**Comment by Biromain** [comment]
Fixed

**Comment by cr2a-graphique** [comment]
fixed par quoi ?

**Comment by Biromain** [comment]
Par rien, ça fonctionnait déjà. Je pense juste que La team traduction "Français" devrait renommer : 
`show_category_heading_title_text` = "Texte des sous-catégories" en "Titre des sous-catégories"

**Comment by cr2a-graphique** [comment]
ok, merci
