### ISSUE TITLE
Contrast des INPUT de saisie insuffisants

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#27]
#555
#fff

Testé avec CCA

**Comment by cr2a-graphique** [comment]
lol les issues sont de plus en plus pragmatique ...

**Comment by cr2a-graphique** [comment]
Ton outil n'est pas fiable.
Résultat du test : 
couleur de fond : #FFFFFF
couleur du texte : #555555
Contraste : 7.45518 :+1: 

Le contraste est valide [AAA]
