### ISSUE TITLE
Revoir l'accessibilité des images d'intros

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#28]
pas de <a>

**Comment by cr2a-graphique** [comment]
... pas de bras pas de :chocolate_bar:

**Comment by cr2a-graphique** [comment]
Pour répondre a l'issue
http://blog.atalan.fr/div-dans-a-et-voiceover-ios/

**Comment by cr2a-graphique** [comment]
Une proposition est à présent en place voir 31a501916e2a46765d5ad080fa8e0853b3fdad71 : 
#### Code détaillé : 
```
<div class="pull-left item-image">
   <a href="/joomla3/index.php/fr/article-category-list/8-beginners"> <!-- (voir point 1) -->
      <div class="item-image-bloc" aria-hidden="true">  <!-- (voir point 2a) -->
         <img itemprop="thumbnailUrl" alt="" src="/joomla3/images/sampledata/mr-geek-600x356.jpg"> <!-- (voir point 2b) -->
         <div class="fxfadeInUp">+</div>
      </div>
      <div class="page-header" role="presentation"> <!-- (voir point 3) -->
         <h3> Beginners </h3>
      </div>
   </a>
</div>
```
- **point 1** : Le lien comporte des élément HTML, valide car :  
w3c html5 : [element ```<a>```](http://www.w3.org/TR/2014/REC-html5-20141028/text-level-semantics.html#the-a-element)  

> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links). This example shows how this can be used to make an entire advertising block into a link:  

- **point 2a** :  aria-hidden="true" non lu par les lecteurs d'écran
- **point 2b** : alt vide car image purement décorative.

**Comment by cr2a-graphique** [comment]
Je clos et re-teste sur la version 1.1.4 en fonction des dernières modifications f100d8084cb74b1064fc064070b98c5296889e82
