### ISSUE TITLE
Paramètre "Position des informations" dans l'article

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#30]
La 'position-8' passe sous la colonne centrale si Position des informations est à "Diviser" dans la config générale pour les articles.

**Comment by cr2a-graphique** [comment]
### Étapes pour reproduire le problème
Affichage front : page article seul.
Configuration générale des articles avec option Position des informations sur Diviser.

### Résultat Actuel
Sur une page article seul, La 'position-8' passe sous la colonne centrale.

### Résultat attendu
La position-8 doit rester a droite.

### Commentaires.
un ```</div>``` en trop dans la condition de partage des informationsgénère le bug.
De plus un div a été ajouté pour cibler ces élément (nombre affichage et tag).
Fichier  template_RGAA_C3rb/html/com_content/article/default.php
