### ISSUE TITLE
Redimensionnement des images d'introduction dans un blog de catégorie.

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#35]
Le problème survient dans l'affichage d'un blog de catégorie, dans les introductions d'articles.

Toute image intégrée  dans l'introduction des articles n'est pas redimensionnée suivant l'espace disponible.

**Comment by cr2a-graphique** [comment]
idem  #37 devrait être correct a présent, a tester
