### ISSUE TITLE
Images responsives

### ISSUE THREAD

**Issue by Ludovic-C3rb** [c3rb-org/template_RGAA_C3rb#36]
Serait-il possible s'ajouter dans le template par défaut un max-width 100% pour rendre les images responsives au niveau des modules contenus personnalisés et au niveau de l'affichage au format blog?

.blog-featured, .blog{ .item {max-width: 100%;}}
.custom{max-width: 100%;}

**Comment by cr2a-graphique** [comment]
normalement en place, a tester

**Comment by Ludovic-C3rb** [comment]
Étapes pour reproduire le problème ( Steps to reproduce the issue )
Mettre une image plus grande que le bloque qui la contient.

Résultat Actuel ( Actual result )
Les image font bien une largeur maximale de 100% mais se déforment.

Résultat attendu ( Expected result )
Il faudrait que la taille maximale des image change au rétrécissement de la fenêtre sans déformation.

Commentaires ( Additional comments )
Il faudrait rajouter un height: auto

**Comment by Ludovic-C3rb** [comment]
Cela est corrigé en dernière version, testé avec cr2a-graphique.
