### ISSUE TITLE
Prise en compte du paramètre Style CSS du lien

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#37]
Lien de Menu > Type de liens > Style CSS du lien ne remonte pas dans les ```<li>``` de notre template.

**Comment by cr2a-graphique** [comment]
#### La gestion du menu a été revu comme suit : 
**Cas sans image :** 
pas d'```<img>``` d'inséré
**Cas avec ```title``` renseigné dans l'administration**
Le title remonte corectement
**Cas sans ```title``` renseigné dans l'administration**
pas de title dutout dans le code
**Cas page active :**
Si title renseigné on récupère le title et on ajoute "- page active" 
Si title non renseigné on affiche le titre de page avec "- page active"

**Cas avec image :**  
```<img>``` inséré avant le texte du lien sans ```alt``` car image décorative avec un aria-hidden=true pour bypass les lecteurs d'écrans.
Si le titre n'est pas affiché, il est inséré avec un sr-only pour ne pas laisser le lien vide.
