### ISSUE TITLE
Positionnement de l'image d'introduction sous le titre des articles.

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#39]
Par défaut, l'image d'introduction associée à un article s'affiche au dessus, dans le cadre d'un affichage blog de catégorie. 

Proposer le positionnement de toutes les images d'intro sous le titre.

**Comment by cr2a-graphique** [comment]
Quelq'un a t'il des contres-indications, @Fuzariane  ?
je l'avais pensé comme ca. Avec image, titre puis texte.

**Comment by Fuzariane** [comment]
Il faut prévoir une bibliothèque de vue avec images TITRE > IMAGES > TEXTE INTRO dans la colonne  vue blog 3 colonnes.

**Comment by cr2a-graphique** [comment]
> Il faut prévoir une bibliothèque de vue
Non réalisable ce jour

----

Un nouveau systeme est en place en version 1.1.4
