### ISSUE TITLE
Style de template

### ISSUE THREAD

**Issue by Ludovic-C3rb** [c3rb-org/template_RGAA_C3rb#41]
Serait il possible dans la gestion des templates d'avoir une configuration pour définir la taille de toutes les bordures.

**Comment by jeromec3rb** [comment]
Serait-il également possible de paramétrer l'arrondi des bordures depuis la gestion du template ?

**Comment by jeromec3rb** [comment]
J'ajoute ce point également :

Actuellement, lorsqu'on crée un lien de menu de type "Blog de catégorie", on obtient une page avec, par exemple, des intros d'articles, qui ne se distinguent pas : 
Un cadre définit le contenu, les intros se retrouvent à l'intérieur de ce cadre sans se distinguer par une bordure.

Le cas étant variable d'un portail à l'autre, est-il possible de proposer une option dans la gestion du template, permettant de choisir entre l'affichage actuel et celui ci-dessous : 

Sur une page "Blog de catégorie", on aurait les intros d'articles distinguées par une bordure et un fond pour chacun.

**Comment by cr2a-graphique** [comment]
> Sur une page "Blog de catégorie", on aurait les intros d'articles distinguées par une bordure et un fond pour chacun.

Pour l'instant mis de coté car trop de cas a gérer.

Pour le reste (arrondi bordure des bloc, des module ) c'est ok
