### ISSUE TITLE
Pb fichier de Langues bouton impression d'article

### ISSUE THREAD

**Issue by Fuzariane** [c3rb-org/template_RGAA_C3rb#43]
![_2015-12-11_10-57-33](https://cloud.githubusercontent.com/assets/8916528/11740911/f41d34ce-9ff5-11e5-92a2-866cfcf63985.png)

**Comment by cr2a-graphique** [comment]
Idem :  JText KO dans la roue crantée des articles #29 précédemment communiqué.
Corrigé dans :  1fb6ef1  /  20 days ago
Dispo dans la version 1.1.3
