### ISSUE TITLE
Liens d'évitement & taille de la font inaccessibles en frontend.

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#47]
Les liens doivent être affichés par défaut.

Cependant, sur le frontend, on retrouve bien ces liens depuis l'inspecteur, mais ces derniers ne sont pas visibles. (Ils se retrouvent en fond sous un module de logo, par exemple).

Est-il possible de rétablir l'affichage par défaut des liens d'évitements ?

**Comment by cr2a-graphique** [comment]
> Les liens doivent être affichés par défaut

Non, si les liens doivent être affichés sur le site alors ajoute un menu standard à ton site et désactive les liens d'évitements dans l'administration du template pour éviter les doublon.

> Cependant, sur le frontend, on retrouve bien ces liens depuis l'inspecteur, mais ces derniers ne sont pas visibles. (Ils se retrouvent en fond sous un module de logo, par exemple).

La correction est en place pour la future version (1.1.4) e268290 : 

> Est-il possible de rétablir l'affichage par défaut des liens d'évitements ?

l'affichage est correct à présent et doublé d'une configuration (voir wiki )
