### ISSUE TITLE
Module de recherche rapide : adapter la largeur de l'input.

### ISSUE THREAD

**Issue by jeromec3rb** [c3rb-org/template_RGAA_C3rb#48]
Actuellement, si je crée un module de recherche rapide et le place dans une position autre que 7 et 8 (colonnes gauche et droite). j'obtiens un module dont le champ de recherche est de taille fixe et bien inférieur à la largeur du module-même.

Est-il possible que la largeur de l'input se fasse en fonction de celle du module de recherche ?

**Comment by cr2a-graphique** [comment]
Cette issue releve une erreur lié a un module non natif de Joomla3
